# Copyright (c) karl-cardenas-coding
# SPDX-License-Identifier: Apache-2.0

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: primary
    ldflags:
      - -s -w -X github.com/karl-cardenas-coding/mywhoop/cmd.VersionString={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - '6'
      - '7'
upx:
  - 
    enabled: true
    compress: best
    goos: [linux, darwin]


archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  split: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      
report_sizes: true