name: Pull Request

on:
  push:
    branches-ignore: [main]


env: 
  GO_VERSION: "1.22"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
        id: go

      - name: "Get dependencies"
        id: dependencies
        run: |
            go get

      - name: Go Tests
        run: |
          make tests-coverage

  lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5.0.1
          with:
            go-version: ${{ env.GO_VERSION }}
            check-latest: true
          id: go

        - name: "Get dependencies"
          id: dependencies
          run: |
              go get

        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v6.0.1
          with:
              args: -v

  compile:
    name: Compile validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
            go-version: ${{ env.GO_VERSION }}
            check-latest: true
        id: go

      - name: "Get dependencies"
        id: dependencies
        run: |
            go get

      - name: build & execute
        run: |
            go build -ldflags="-X 'github.com/karl-cardenas-coding/mywhoop/cmd.VersionString=1.0.0'" -o=mywhoop -v
            ./mywhoop version